preset: none

enabled:
  - align_double_arrow
  - align_equals
  - align_phpdoc
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_before_break
  - blank_line_before_continue
  - blank_line_before_return
  - blank_line_before_throw
  - blank_line_before_try
  - cast_spaces
  - class_definition
  - combine_consecutive_unsets
  - concat_with_spaces
  - elseif
  - encoding
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - long_array_syntax
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - method_visibility_required
  - native_function_casing
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_closing_tag
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_leading_namespace_whitespace
  - no_php4_constructor
  - no_short_echo_tag
  - no_spaces_after_function_name
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_useless_else
  - no_unneeded_final_method
  - no_unused_imports
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - not_operator_with_space
  - phpdoc_add_missing_param_annotation
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_order
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_types
  - phpdoc_types_order
  - phpdoc_var_without_name
  - property_visibility_required
  - return_type_declaration
  - short_scalar_cast
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_quote
  - standardize_not_equals
  - strict_comparison
  - switch_case_semicolon_to_colon
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - unix_line_endings
  - whitespace_after_comma_in_array

finder:
  not-path:
    - "libraries"
  exclude:
    - "tests"
  name:
    - "*.php"
